### ISSUE TITLE
application would not build from command line

### ISSUE THREAD

**Issue by adultmalehuman** [emmapatterson/multi-module-spring-boot#2]
Application would not build from command line when I did: `./gradlew clean build`

Gradle could not determine which class with a main() method was the application entry point.

I edited the 'backend' build.gradle.kts and added the application plugin. It now looks like this:

```
plugins {
    id("org.springframework.boot")
    id("application")

    kotlin("jvm")
    kotlin("plugin.spring")
}

application {
    this.mainClassName = "com.kotlin.multimodulespringboot.MultiModuleSpringBootApplication"
}

dependencies {
    implementation(project(":test-utils"))

    implementation(kotlin("reflect"))
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
}
```

**Comment by emmamoinat** [comment]
Just delete the extra main method that I added just to show it works using a method from the utils module. Then you’ll be grand without this addition plugin.

**Comment by emmamoinat** [comment]
I have just removed this second main method as it was only for an example and was expecting people to remove it. If you try it now, you should be grand. Let me know

**Comment by adultmalehuman** [comment]
Thanks Emma! I was using your repo as a reference while learning to create a multi-project Gradle build. I didn't really look at your source code, as I was only interested in your Gradle config and your use of the Kotlin DSL for Gradle. It was very helpful, so thanks for putting this on Github! :)

**Comment by emmamoinat** [comment]
Absolutely no problem at all! Happy to help 😊 let me know if you have any questions at all!
